title: Diego Bernal
me: Diego Bernal
location: Coachella Valley, California
favicon: assets/images/favicon.ico
profileImage: assets/images/profile.jpg
ogTitle: Hola! I'm Diego
ogType: website
ogDescription: I'm Diego, web developer and front-end engineer
ogImage: assets/images/godiego-preview.png
ogUrl: https://www.godiego.me/
email: hola@godiego.me
linkedInUrl: https://www.linkedin.com/in/dbernal91/
facebookUrl: https://www.facebook.com/diego.bernal.91
githubUrl: https://github.com/go-diego
googleAnalyticsId: UA-116050053-1
markdown: kramdown
plugins:
  - jemoji
jekyll-timeago:
  depth: 1
include: [_pages]
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - node_modules
  - package-lock.json
  - src
