[build]
    publish = "out"
    command = "npm run export"
    functions = "src/functions"
[dev]
    command = "npm run dev"
[context.development]
    environment = { NODE_ENV = "development",  GA_ID = "0" }
